### ISSUE TITLE
Updating the examples with testimages other than lena

### ISSUE THREAD

**Issue by ashwanirathee** [roflmaostc/Noise.jl#4]
Hey @roflmaostc,I came to know about Noise.jl when I was trying to solve a problem of mine that needed adding random noise to the image.
I saw that the documentation uses Lena as the test image  in every portion
JuliaImages,I believe doesn't use Lena anymore following the discussion https://github.com/JuliaImages/TestImages.jl/issues/72

I would be happy to update the documentation with different test images if you think there is a need,.It's a fairly easy task which I believe you would have changed yourself only if you wanted that.But still opened the discussion just in case if you needed help with it.

**Comment by roflmaostc** [comment]
You're totally right. When I was creating this package, I wasn't aware of it :disappointed: 
I'll fix ASAP.

**Comment by roflmaostc** [comment]
After messing with the migration to GitHub Actions, I released v0.2.2

https://github.com/JuliaRegistries/General/pull/26419
