### ISSUE TITLE
Complex signals not handled correctly

### ISSUE THREAD

**Issue by JeffFessler** [roflmaostc/Noise.jl#8]
```julia
add_gauss(ones(ComplexF32,5))

5-element Vector{ComplexF32}:
  1.116043f0 + 0.0f0im
 0.7947307f0 + 0.0f0im
 0.9210193f0 + 0.0f0im
 1.0018466f0 + 0.0f0im
 0.9741812f0 + 0.0f0im
```

Noise should be added to _both_ the real and imaginary part.
And the associated documentation should specify whether `σ` refers to the standard deviation of the real and imaginary parts, or whether it refers to the standard deviation of the complex variable (there is a factor of 2 to consider; either way is fine as long as it is documented).  See
https://en.wikipedia.org/wiki/Complex_normal_distribution

**Comment by roflmaostc** [comment]
Thanks for raising that issue.

The easiest fix (for me) would be introducing a complex `\sigma`. 
Does that make sense? 

The code would look then like
```julia
julia> using Statistics, Noise

julia> @time add_gauss(zeros(ComplexF32, (1,5)),1)
  0.000005 seconds (2 allocations: 256 bytes)
1×5 Matrix{ComplexF32}:
 -1.39042+0.0im  -0.556938+0.0im  -0.0182292+0.0im  0.884261+0.0im  0.967371+0.0im

julia> @time add_gauss(zeros(ComplexF32, (1,5)),1im)
  0.000006 seconds (2 allocations: 256 bytes)
1×5 Matrix{ComplexF32}:
 0.0+0.871712im  0.0+0.63515im  0.0+0.199782im  0.0-1.64308im  0.0+1.93661im

julia> @time add_gauss(zeros(ComplexF32, (1,5)),1im + 1)
  0.000008 seconds (2 allocations: 256 bytes)
1×5 Matrix{ComplexF32}:
 -0.139775-0.139775im  -2.3007-2.3007im  -1.11405-1.11405im  -0.872196-0.872196im  1.02117+1.02117im

julia> @time add_gauss(zeros(ComplexF32, (1,5000)),1im) |> imag |> std
  0.000102 seconds (6 allocations: 97.922 KiB)
1.0119475f0

julia> @time add_gauss(zeros(ComplexF32, (1,5000)),1) |> real |> std
  0.000230 seconds (6 allocations: 97.922 KiB)
1.0125026f0

julia> @time add_gauss(zeros(ComplexF32, (1,5000)),1im + 1) |> std
  0.000145 seconds (4 allocations: 78.281 KiB)
1.4158667f0
```

Or do you have in mind that the the noise term is the same for real and imaginary part?
Namely
```julia
julia> randn() * 1 + randn() * 1im 
-0.9419225158663372 - 1.4876992986290218im

julia> randn() * (1 + 1im)
-0.35788356791304854 - 0.35788356791304854im
```
Of course, both could be added, but we would need a mechanism to distinguish between both

**Comment by JeffFessler** [comment]
I definitely think the default (for a real \sigma input) should be the form `randn() * 1 + randn() * 1im` because that is what is consistent with a complex normal distribution.
Your use of a complex \sigma would be fine for the (probably rare) cases where someone wants a different variance for the two components.

It should be easy to distinguish the two using dispatch.
Roughly speaking, after you implement a method like
`add_gauss(something, sigma::Complex{T}) where T <: Real`
Then we can just add the method
`add_gauss(something::AbstractArray{Complex{T}} where T <: Real, sigma::Real) =
add_gauss(something, sigma + 1im * sigma)`

Personally I'd probably add another kwarg like `imsigma` for the imaginary part, rather than putting it in sigma, but it doesn't really matter since most people will only use the default anyway.

I looked at Distributions.jl for guidance but CN is still a WIP there:
https://github.com/JuliaStats/Distributions.jl/issues/1149
However, if you look at the code there, it "only" provides the case where the real/imag parts have the same variance so that's another reason to just focus on that case.

BTW, I think if you dispatch on something like `add_gauss(something::AbstractArray{Complex{T}} where T <: Real, ...)` then it should be an easy addition?

**Comment by roflmaostc** [comment]
I'll try to come up with something this weekend.

I need to change some internal structures (the whole Noise.jl code base is somehow messy because of this RGB and Gray types, which bury the *real* element type quite deep) so it might take a little bit, but let's see how far I can come :)

**Comment by roflmaostc** [comment]
I pushed a new commit. It is a breaking release for Noise.jl, so 0.3.0

```julia
julia> using Statistics, Noise

julia> z = zeros(ComplexF32, (1000, 1000));

julia> @time add_gauss(z,42)  |> imag |> std
  0.043315 seconds (5 allocations: 11.444 MiB)
41.933495f0

julia> @time add_gauss(z,42)  |> real |> std
  0.038703 seconds (5 allocations: 11.444 MiB)
42.061054f0

julia> @time add_gauss(z,42+21im)  |> imag |> std
  0.072160 seconds (58.30 k allocations: 15.133 MiB, 67.05% compilation time)
21.000574f0

julia> @time add_gauss(z,42+21im)  |> real |> std
  0.026835 seconds (5 allocations: 11.444 MiB)
41.933743f0
```

Is that the behavior you're expecting?
The same also holds for `\mu`
```julia
julia> @time add_gauss([0im] ,0, 1) 
  0.000003 seconds (2 allocations: 192 bytes)
1-element Vector{Complex{Int64}}:
 1 + 1im

julia> @time add_gauss([0im] ,0, 1+0im)
  0.000004 seconds (2 allocations: 192 bytes)
1-element Vector{Complex{Int64}}:
 1 + 0im
```

**Comment by JeffFessler** [comment]
Yes, that behavior looks appropriate.  I had trouble following all the changes in the different commits, but if you make it a PR then I should be able to review and confirm if you'd like.  Thanks!

**Comment by roflmaostc** [comment]
No worries, I just release version 0.3.0. Noise.jl was my first Julia project, so the code is not very sophisticated (and probably not worth much investment)

Tests confirm that new behavior is the same for real arrays and a few tests confirm that it works for complex.
